{"values()":{"org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory$2":["<clinit>()"]},"<init>(java.lang.String, int)":{"org.bukkit.event.block.Action":["<clinit>()","<clinit>()","<clinit>()","<clinit>()","<clinit>()"]},"ordinal()":{"org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory":["callPlayerInteractEvent()"],"org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory$2":["<clinit>()","<clinit>()"]}}